### ISSUE TITLE
Make kubectl-ingress available via `krew`

### ISSUE THREAD

**Issue by corneliusweig** [InfraBuilder/kubectl-ingress#1]
:wave: Hello, maintainer of the kubectl plugin manager krew here (https://github.com/kubernetes-sigs/krew).

What do you think of distributing this as a kubectl plugin via `krew`?

Why?

- kubectl plugins are becoming a thing now, we have over 30 plugins.
- krew helps you package/distribute your tool on macOS, Linux and Windows so you don't deal with homebrew, apt/dnf, chocolatey etc separately.
- krew makes your plugin more discoverable.

I suspect there would be no code changes required. The release process would involve periodic updates to the plugin manifest file hosted at https://github.com/kubernetes-sigs/krew-index/tree/master/plugins.

If you want to go ahead, please open a pull request for a plugin manifest in https://github.com/kubernetes-sigs/krew-index/. It could be that the plugin name `ingress` will not be accepted (please see our naming guide https://github.com/kubernetes-sigs/krew/blob/master/docs/NAMING_GUIDE.md for that). I think `ingressctl` would be more appropriate. But we can discuss in the PR.

**Comment by AlexisDucastel** [comment]
Hi @corneliusweig !

It will be a pleasure, I'll check this asap. 

I understand you point on the plugin name, I agress that it would reduce collisions with K8S own resources. I think I'll fork this repo to a new repo with the new name (kubectl-ingressctl). 

By the way, thanks for providing such a good tool as krew ! Very useful :)

**Comment by corneliusweig** [comment]
Hey, glad you like it, although the master mind behind this is ahmetb.

You don't have to fork your repo. There are a few plugins which are available under different names in krew. For example `rakkess` - > `access-matrix`. The only downside is that the `-h` command help uses the wrong name. But this is acceptable in most cases.

**Comment by AlexisDucastel** [comment]
Closing this issue, this repo is now obsolete and archived as the official kubectl cli does manage ingress right now
